#!/usr/bin/env bash
# Compile the GPU renderer's GLSL shaders to SPIR-V and embed them as C headers.
# The generated *.spv.h files are committed, so a normal build needs no shader
# compiler; run this only after editing a shader in LIB386/SYSTEM/SHADERS/.
set -euo pipefail

cd "$(dirname "$0")/../../LIB386/SYSTEM/SHADERS"

if ! command -v glslc >/dev/null 2>&1; then
    echo "glslc not found (install shaderc / the Vulkan SDK)" >&2
    exit 1
fi

for src in *.vert *.frag; do
    name="${src//./_}"
    tmp="$(mktemp)"
    glslc -O --target-env=vulkan1.0 "$src" -o "$tmp"
    {
        echo "/* Generated by scripts/dev/build-gpu-shaders.sh from $src. Do not edit. */"
        echo "#pragma once"
        echo "static const unsigned char ${name}_spv[] = {"
        xxd -i < "$tmp"
        echo "};"
        echo "static const unsigned int ${name}_spv_len = sizeof(${name}_spv);"
    } > "$src.spv.h"
    rm -f "$tmp"
    echo "$src -> $src.spv.h"
done

# The composite's half-resolution pass: the same source built with HALF_PASS.
tmp="$(mktemp)"
glslc -O --target-env=vulkan1.0 -DHALF_PASS COMPOSITE.frag -o "$tmp"
{
    echo "/* Generated by scripts/dev/build-gpu-shaders.sh from COMPOSITE.frag with HALF_PASS. Do not edit. */"
    echo "#pragma once"
    echo "static const unsigned char COMPOSITE_HALF_frag_spv[] = {"
    xxd -i < "$tmp"
    echo "};"
    echo "static const unsigned int COMPOSITE_HALF_frag_spv_len = sizeof(COMPOSITE_HALF_frag_spv);"
} > COMPOSITE_HALF.frag.spv.h
rm -f "$tmp"
echo "COMPOSITE.frag (HALF_PASS) -> COMPOSITE_HALF.frag.spv.h"
