#!/usr/bin/env python3
"""Bakes the modern menu font (Nunito, SIL OFL 1.1) into a signed distance
field atlas header, LIB386/SYSTEM/FONTS/NUNITO_SDF.H.

A distance field keeps glyph edges sharp at any on-screen size, so one small
atlas serves every resolution from 640x480 to 4K; UIOVERLAY.CPP turns it into
coverage at the size the menu is drawn.

    python3 -m pip install pillow numpy scipy
    curl -L -o Nunito.ttf "https://github.com/google/fonts/raw/main/ofl/nunito/Nunito%5Bwght%5D.ttf"
    scripts/dev/build-menu-font.py Nunito.ttf

The glyph set is ASCII, Latin-1 and every code point the game's CP850 text
maps to (read from LIB386/SYSTEM/STRING.CPP).
"""
import os
import re
import sys

import numpy as np
from PIL import Image, ImageDraw, ImageFont
from scipy.ndimage import distance_transform_edt

EM = 48          # nominal pixel size of the field
SPREAD = 6       # distance range encoded, in field pixels, each side of the edge
SUPER = 4        # supersampling of the source raster
WEIGHT = 700     # Nunito Bold
ATLAS_W = 1024

root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ttf = sys.argv[1]

codes = set(range(32, 127)) | set(range(160, 256))
codes |= {0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x2039, 0x203A, 0x20AC, 0x0152, 0x0153}
with open(os.path.join(root, "LIB386/SYSTEM/STRING.CPP"), encoding="utf-8") as f:
    codes |= {int(m, 16) for m in re.findall(r"case 0x([0-9A-Fa-f]+):", f.read())}

big = ImageFont.truetype(ttf, EM * SUPER)
try:
    big.set_variation_by_axes([WEIGHT])
except Exception:
    pass
ascent, descent = big.getmetrics()

glyphs = []
for cp in sorted(codes):
    ch = chr(cp)
    if cp != 32 and big.getmask(ch).getbbox() is None:
        continue
    advance = big.getlength(ch) / SUPER
    bbox = big.getbbox(ch)  # relative to the top of the ascent line
    if cp == 32 or bbox[2] <= bbox[0]:
        glyphs.append((cp, None, 0, 0, advance))
        continue
    pad = SPREAD * SUPER
    w = bbox[2] - bbox[0] + 2 * pad
    h = bbox[3] - bbox[1] + 2 * pad
    w += (-w) % SUPER
    h += (-h) % SUPER
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((pad - bbox[0], pad - bbox[1]), ch, font=big, fill=255)
    inside = np.array(img) >= 128
    dist = distance_transform_edt(~inside) - distance_transform_edt(inside)  # > 0 outside
    dist /= SUPER
    small = dist.reshape(h // SUPER, SUPER, w // SUPER, SUPER).mean(axis=(1, 3))
    field = np.clip(128.0 - small * (127.0 / SPREAD), 0, 255).astype(np.uint8)
    left = (bbox[0] - pad) / SUPER
    top = (bbox[1] - pad) / SUPER
    glyphs.append((cp, field, left, top, advance))

# Shelf packing.
x = y = shelf = 0
placed = []
for cp, field, left, top, advance in glyphs:
    if field is None:
        placed.append((cp, 0, 0, 0, 0, left, top, advance))
        continue
    h, w = field.shape
    if x + w + 1 > ATLAS_W:
        x, y, shelf = 0, y + shelf + 1, 0
    placed.append((cp, x, y, w, h, left, top, advance))
    x += w + 1
    shelf = max(shelf, h)
atlas_h = y + shelf + 1
atlas_h += (-atlas_h) % 4
atlas = np.zeros((atlas_h, ATLAS_W), np.uint8)
for (cp, gx, gy, w, h, *_), (_, field, *_) in zip(placed, glyphs):
    if field is not None:
        atlas[gy:gy + h, gx:gx + w] = field

out = os.path.join(root, "LIB386/SYSTEM/FONTS/NUNITO_SDF.H")
with open(out, "w") as f:
    f.write("/* Generated by scripts/dev/build-menu-font.py: do not edit.\n")
    f.write(" * Nunito, Copyright 2014 The Nunito Project Authors, SIL Open Font License 1.1\n")
    f.write(" * (Nunito-OFL.txt next to this file). Signed distance field, 128 on the edge. */\n")
    f.write("#pragma once\n\n")
    f.write(f"#define NUNITO_SDF_EM {EM}\n#define NUNITO_SDF_SPREAD {SPREAD}\n")
    f.write(f"#define NUNITO_SDF_ASCENT {ascent / SUPER:.3f}f\n#define NUNITO_SDF_DESCENT {descent / SUPER:.3f}f\n")
    f.write(f"#define NUNITO_SDF_ATLAS_W {ATLAS_W}\n#define NUNITO_SDF_ATLAS_H {atlas_h}\n")
    f.write(f"#define NUNITO_SDF_GLYPHS {len(placed)}\n\n")
    f.write("typedef struct {\n    unsigned short Code, X, Y, W, H;\n    float Left, Top, Advance;\n} T_NUNITO_GLYPH;\n\n")
    f.write("static const T_NUNITO_GLYPH NunitoGlyphs[NUNITO_SDF_GLYPHS] = {\n")
    for cp, gx, gy, w, h, left, top, advance in placed:
        f.write(f"    {{{cp}, {gx}, {gy}, {w}, {h}, {left:.2f}f, {top:.2f}f, {advance:.2f}f}},\n")
    f.write("};\n\nstatic const unsigned char NunitoAtlas[NUNITO_SDF_ATLAS_W * NUNITO_SDF_ATLAS_H] = {\n")
    flat = atlas.reshape(-1)
    for i in range(0, len(flat), 32):
        f.write("    " + ",".join(str(v) for v in flat[i:i + 32]) + ",\n")
    f.write("};\n")
print(f"{len(placed)} glyphs, atlas {ATLAS_W}x{atlas_h}, {out}")
